import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  pokedex: defineTable({
    dexNumber: v.optional(v.union(v.number(), v.null())),
    name: v.optional(v.union(v.string(), v.null())),
    type1: v.optional(v.union(v.string(), v.null())),
    type2: v.optional(v.union(v.string(), v.null())),
    national_number: v.optional(v.union(v.number(), v.null())),
    english_name: v.optional(v.union(v.string(), v.null())),
    primary_type: v.optional(v.union(v.string(), v.null())),
    secondary_type: v.optional(v.union(v.string(), v.null())),
    gen: v.optional(v.union(v.string(), v.null())),
    abilities_0: v.optional(v.union(v.string(), v.null())),
    abilities_1: v.optional(v.union(v.string(), v.null())),
    abilities_2: v.optional(v.union(v.string(), v.null())),
    abilities_hidden: v.optional(v.union(v.string(), v.null())),
    against_bug: v.optional(v.union(v.number(), v.string(), v.null())),
    against_dark: v.optional(v.union(v.number(), v.string(), v.null())),
    against_dragon: v.optional(v.union(v.number(), v.string(), v.null())),
    against_electric: v.optional(v.union(v.number(), v.string(), v.null())),
    against_fairy: v.optional(v.union(v.number(), v.string(), v.null())),
    against_fighting: v.optional(v.union(v.number(), v.string(), v.null())),
    against_fire: v.optional(v.union(v.number(), v.string(), v.null())),
    against_flying: v.optional(v.union(v.number(), v.string(), v.null())),
    against_ghost: v.optional(v.union(v.number(), v.string(), v.null())),
    against_grass: v.optional(v.union(v.number(), v.string(), v.null())),
    against_ground: v.optional(v.union(v.number(), v.string(), v.null())),
    against_ice: v.optional(v.union(v.number(), v.string(), v.null())),
    against_normal: v.optional(v.union(v.number(), v.string(), v.null())),
    against_poison: v.optional(v.union(v.number(), v.string(), v.null())),
    against_psychict: v.optional(v.union(v.number(), v.string(), v.null())),
    against_rock: v.optional(v.union(v.number(), v.string(), v.null())),
    against_steel: v.optional(v.union(v.number(), v.string(), v.null())),
    against_water: v.optional(v.union(v.number(), v.string(), v.null())),
    base_egg_steps: v.optional(v.union(v.number(), v.string(), v.null())),
    capture_rate: v.optional(v.union(v.number(), v.string(), v.null())),
    classification: v.optional(v.union(v.string(), v.null())),
    description: v.optional(v.union(v.string(), v.null())),
    evochain_0: v.optional(v.union(v.string(), v.null())),
    evochain_1: v.optional(v.union(v.string(), v.null())),
    evochain_2: v.optional(v.union(v.string(), v.null())),
    evochain_3: v.optional(v.union(v.string(), v.null())),
    evochain_4: v.optional(v.union(v.string(), v.null())),
    evochain_5: v.optional(v.union(v.string(), v.null())),
    evochain_6: v.optional(v.union(v.string(), v.null())),
    gigantamax: v.optional(v.union(v.string(), v.null())),
    height_m: v.optional(v.union(v.number(), v.string(), v.null())),
    is_legendary: v.optional(v.union(v.number(), v.string(), v.null())),
    is_mythical: v.optional(v.union(v.number(), v.string(), v.null())),
    is_sublegendary: v.optional(v.union(v.number(), v.string(), v.null())),
    japanese_name: v.optional(v.union(v.string(), v.null())),
    mega_evolution: v.optional(v.union(v.string(), v.null())),
    mega_evolution_alt: v.optional(v.union(v.string(), v.null())),
    percent_female: v.optional(v.union(v.number(), v.string(), v.null())),
    percent_male: v.optional(v.union(v.number(), v.string(), v.null())),
    weight_kg: v.optional(v.union(v.number(), v.string(), v.null())),
    sp_attack: v.optional(v.union(v.number(), v.string(), v.null())),
    sp_defense: v.optional(v.union(v.number(), v.string(), v.null())),
    generation: v.optional(v.union(v.number(), v.string(), v.null())),
    hp: v.optional(v.union(v.number(), v.string(), v.null())),
    attack: v.optional(v.union(v.number(), v.string(), v.null())),
    defense: v.optional(v.union(v.number(), v.string(), v.null())),
    specialAttack: v.optional(v.union(v.number(), v.string(), v.null())),
    specialDefense: v.optional(v.union(v.number(), v.string(), v.null())),
    speed: v.optional(v.union(v.number(), v.string(), v.null()))
  })
    .index("by_dex_number", ["dexNumber"])
    .index("by_name", ["name"])
    .index("by_type1_and_name", ["type1", "name"])
    .index("by_generation_and_dex_number", ["generation", "dexNumber"])
});
